name: Docker Build and Push

on:
  push:
    branches:
      - main  # Runs the workflow when pushing to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Debugging Step - Check if Secrets Exist
    - name: Check Secrets
      run: |
        echo "DOCKER_USERNAME is set"
        echo "DOCKER_PASSWORD is set"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Alternative Login (if needed)
    - name: Alternative Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .  # Use the current directory as the build context
        file: ./Dockerfile  # Ensure the correct path to Dockerfile
        push: true
        tags: abderahman2000/my-web-app:latest

    # Check Docker Hub Rate Limit (if experiencing issues)
    - name: Check Docker Rate Limit
      run: |
        curl -s --head https://hub.docker.com || echo "Rate limit check skipped"
